### ISSUE TITLE
Undefined symbol when running disclocker-find

### ISSUE THREAD

**Issue by ageis** [Aorimn/dislocker#172]
Looks like this may be a duplicate of #96. I am running Debian sid/buster Linux 5.0.1 x86_64 and Ruby 2.5.3.
```
Traceback (most recent call last):
	2: from /usr/local/bin/dislocker-find:26:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /usr/local/lib/libdislocker.so: undefined symbol: Init_libdislocker - /usr/local/lib/libdislocker.so (LoadError)
```

**Comment by TheAlienDrew** [comment]
@Aorimn from what I understand, I think that dislocker is packaged fine, but the libdislocker0 is what needs to be repackaged.

It's still pointing to version 0.7.1, instead of the latest 0.7.2 that shows up in this repo, which I imagine is the reason why it's spitting out an error about a symbol it can't find.

**Comment by TheAlienDrew** [comment]
Also, this appears to be directly related to https://github.com/Aorimn/dislocker/issues/220
