### ISSUE TITLE
"undefined symbol: Init_libdislocker" when running dislocker-find

### ISSUE THREAD

**Issue by stevenshiau** [Aorimn/dislocker#220]
I ran "dislocker-find" from  on Debian Sid, and got an error. The related info:
steven@sid-amd64:~$ dpkg -l dislocker
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-==================================>
ii  dislocker      0.7.1-5      amd64        read/write encrypted BitLocker vol>

steven@sid-amd64:~$ dislocker-find -h
Traceback (most recent call last):
2: from /usr/bin/dislocker-find:26:in `<main>`
1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': /usr/lib/libdislocker.so: undefined symbol: Init_libdislocker - /usr/lib/libdislocker.so (LoadError)

`steven@sid-amd64:~$ ls -l /usr/lib/libdislocker.so`
lrwxrwxrwx 1 root root 21 Nov 15  2019 /usr/lib/libdislocker.so -> libdislocker.so.0.7.1
steven@sid-amd64:~$ ls -l /usr/lib/libdislocker.so.0.7.1
-rw-r--r-- 1 root root 98K Nov 15  2019 /usr/lib/libdislocker.so.0.7.1

If you need more info, please let me know. Thanks.

**Comment by SimonHeimberg** [comment]
A same error has been reported to debian as well: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906430

**Comment by TheAlienDrew** [comment]
@SimonHeimberg if you know how to compile dislocker, it can work then. I think the issue that Aorimn looked over is not recompiling a new version of libdislocker0.7, since it appears the newer dislocker-fuse is looking for a new variable in the libdislocker 0.7.2 version, that just isn't in the 0.7.1 version that is currently packaged.
