### ISSUE TITLE
Cannot run on OSX: Error during reading the volume: not enough byte read

### ISSUE THREAD

**Issue by Thomas-Negrault** [Aorimn/dislocker#253]
I'm trying to read my windows SDD on my Mac `11.2.3 (20D91)`
First I had an issue with the installation:

I've cloned the project then ran `brew install src/dislocker.rb`

``` brew install src/dislocker.rb
Error: Failed to load cask: src/dislocker.rb
Cask 'dislocker' is unreadable: wrong constant name #<Class:0x00007fa7b5d0f930>
Warning: Treating src/dislocker.rb as a formula.
==> Downloading https://github.com/Aorimn/dislocker/archive/v0.7.2.zip
Already downloaded: /Users/thomas/Library/Caches/Homebrew/downloads/cc96643f1725aa6a0243a6540a755aa762154ec4f0cda9caa6bf10ee3e83b71e--dislocker-0.7.2.zip
==> cmake
==> make
Last 15 lines from /Users/thomas/Library/Logs/Homebrew/dislocker/02.make:
[ 95%] Linking C executable dislocker-file
cd /tmp/dislocker-20210514-16501-s7wkij/dislocker-0.7.2/src && /usr/local/Cellar/cmake/3.20.2/bin/cmake -E cmake_link_script CMakeFiles/dislocker-file.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang  -fPIC -Wall -Wextra -fstack-protector -fstrict-aliasing -D_FORTIFY_SOURCE=2 -O1 -Qunused-arguments -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -pie -fPIE CMakeFiles/dislocker-file.dir/dislocker-file.c.o -o dislocker-file  -Wl,-rpath,/tmp/dislocker-20210514-16501-s7wkij/dislocker-0.7.2/src libdislocker.0.7.2.dylib -lpthread /usr/local/lib/libmbedcrypto.dylib -framework ruby /usr/local/lib/libfuse.dylib
[ 98%] Linking C executable dislocker-metadata
[ 98%] Linking C executable dislocker-bek
cd /tmp/dislocker-20210514-16501-s7wkij/dislocker-0.7.2/src && /usr/local/Cellar/cmake/3.20.2/bin/cmake -E cmake_link_script CMakeFiles/dislocker-bek.dir/link.txt --verbose=1
cd /tmp/dislocker-20210514-16501-s7wkij/dislocker-0.7.2/src && /usr/local/Cellar/cmake/3.20.2/bin/cmake -E cmake_link_script CMakeFiles/dislocker-metadata.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang  -fPIC -Wall -Wextra -fstack-protector -fstrict-aliasing -D_FORTIFY_SOURCE=2 -O1 -Qunused-arguments -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -pie -fPIE CMakeFiles/dislocker-metadata.dir/dislocker-metadata.c.o -o dislocker-metadata  -Wl,-rpath,/tmp/dislocker-20210514-16501-s7wkij/dislocker-0.7.2/src libdislocker.0.7.2.dylib -lpthread /usr/local/lib/libmbedcrypto.dylib -framework ruby /usr/local/lib/libfuse.dylib
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang  -fPIC -Wall -Wextra -fstack-protector -fstrict-aliasing -D_FORTIFY_SOURCE=2 -O1 -Qunused-arguments -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -pie -fPIE CMakeFiles/dislocker-bek.dir/dislocker-bek.c.o -o dislocker-bek  -Wl,-rpath,/tmp/dislocker-20210514-16501-s7wkij/dislocker-0.7.2/src libdislocker.0.7.2.dylib -lpthread /usr/local/lib/libmbedcrypto.dylib -framework ruby /usr/local/lib/libfuse.dylib
cd /tmp/dislocker-20210514-16501-s7wkij/dislocker-0.7.2/src && mkdir -p /tmp/dislocker-20210514-16501-s7wkij/dislocker-0.7.2/man/
cd /tmp/dislocker-20210514-16501-s7wkij/dislocker-0.7.2/src && gzip -c /tmp/dislocker-20210514-16501-s7wkij/dislocker-0.7.2/man/darwin/dislocker-file.1 > /tmp/dislocker-20210514-16501-s7wkij/dislocker-0.7.2/man/dislocker-file.1.gz
[ 98%] Built target dislocker-metadata
[ 98%] Built target dislocker-bek
[ 98%] Built target dislocker-file
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	26: from /usr/local/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
	25: from /usr/local/Homebrew/Library/Homebrew/build.rb:133:in `install'
	24: from /usr/local/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
	23: from /usr/local/Homebrew/Library/Homebrew/build.rb:138:in `block in install'
	22: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1259:in `brew'
	21: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2318:in `stage'
	20: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	19: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	18: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	17: from /usr/local/Homebrew/Library/Homebrew/resource.rb:199:in `mktemp'
	16: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	15: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	14: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	13: from /usr/local/Homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
	12: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:102:in `stage'
	11: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
	10: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
	 9: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2338:in `block in stage'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2339:in `block (2 levels) in stage'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1266:in `block in brew'
	 4: from /usr/local/Homebrew/Library/Homebrew/build.rb:178:in `block (2 levels) in install'
	 3: from /Users/thomas/Projects/dislocker/src/dislocker.rb:20:in `install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2111:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2111:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2175:in `block in system': Failed executing: make (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:155:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:167:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:494:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:440:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:444:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:66:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)
```

I managed to install it by following https://github.com/Aorimn/dislocker/issues/239#issuecomment-764668344

The disk I'm trying to read seems to be `disk2`
```
diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *251.0 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                 Apple_APFS Container disk1         250.1 GB   disk0s2
                    (free space)                         650.0 MB   -

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +250.1 GB   disk1
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD            18.5 GB    disk1s1
   2:              APFS Snapshot com.apple.os.update-... 18.5 GB    disk1s1s1
   3:                APFS Volume Preboot                 406.3 MB   disk1s2
   4:                APFS Volume Recovery                611.0 MB   disk1s3
   5:                APFS Volume VM                      2.1 GB     disk1s4
   6:                APFS Volume Macintosh HD - Data     214.7 GB   disk1s5

/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *275.1 GB   disk2
   1:           Windows Recovery                         471.9 MB   disk2s1
   2:                        EFI NO NAME                 103.8 MB   disk2s2
   3:         Microsoft Reserved                         16.8 MB    disk2s3
   4:       Microsoft Basic Data                         273.9 GB   disk2s4
   5:           Windows Recovery                         572.5 MB   disk2s5
```
Trying with `/dev/disk2`:
```
-> sudo dislocker -vvv -V /dev/disk2 -u /Volumes/bitlocker-partition1
Password:
Fri May 14 11:32:47 2021 [INFO] dislocker by Romain Coltel, v0.7.2 (compiled for Darwin/x86_64)
Fri May 14 11:32:47 2021 [INFO] Compiled version: master:6bba8a8
Fri May 14 11:32:48 2021 [ERROR] The signature of the volume (м) doesn't match the BitLocker's ones (-FVE-FS- or MSWIN4.1). Abort.
Fri May 14 11:32:48 2021 [CRITICAL] Cannot parse volume header. Abort.
```
Trying with `/dev/disk2s4`:
```
sudo dislocker -vvv -V /dev/disk2s4 /Volumes/bitlocker-partition1 -r -s
Fri May 14 11:33:22 2021 [INFO] dislocker by Romain Coltel, v0.7.2 (compiled for Darwin/x86_64)
Fri May 14 11:33:22 2021 [INFO] Compiled version: master:6bba8a8
Fri May 14 11:33:22 2021 [ERROR] Failed to read in #3: Resource busy
Fri May 14 11:33:22 2021 [CRITICAL] Error during reading the volume: not enough byte read.
```

Am I missing something here ?

**Comment by Xefyr0** [comment]
Also experiencing the installation issue on Catalina. (10.15.7) however, the fix mentioned in #239 didn't work for me.
It's also worth mentioning that trying to install dislocker directly from brew via `brew install dislocker` resulted in the error message `Error: dislocker has been disabled because it requires FUSE!` despite the fact that I have tried this command using both a brew installation of macfuse and a .dmg installation. Installing osxfuse via brew did not resolve that error either.
